const projects = [
  {
    number: '01',
    name: 'Papaya Sector',
    type: 'tool',
    kind: 'Data & analysis',
    status: 'In active build',
    summary: 'A Formula One analysis platform for understanding why a race unfolded the way it did.',
    useCase: 'Turns raw race telemetry and upgrade data into a surface for better questions.',
    tags: ['OpenF1', 'Supabase', 'Next.js'],
    accent: 'orange',
    repoUrl: 'https://github.com/irgendjemandkeinkorper/papaya-sector',
  },
  {
    number: '02',
    name: 'Ætheric Transmuter',
    type: 'tool',
    kind: 'Creative tool',
    status: 'Playable prototype',
    summary: 'A browser workbench that turns images into constrained, elemental sprites for Godot.',
    useCase: 'Bridges visual exploration and game-ready asset export without leaving the browser.',
    tags: ['Pixel art', 'Godot', 'Canvas'],
    accent: 'violet',
    repoUrl: 'https://github.com/irgendjemandkeinkorper/imixelerator',
  },
  {
    number: '03',
    name: 'Semantic Lore Repurposer',
    type: 'tool',
    kind: 'AI utility',
    status: 'Local-first utility',
    summary: 'One raw lore document becomes a journal entry, GM reference sheet, and card-game flavor text.',
    useCase: 'Makes one piece of world-building legible to three different kinds of reader.',
    tags: ['FastAPI', 'OpenAI API', 'Content'],
    accent: 'lime',
    repoUrl: 'https://github.com/irgendjemandkeinkorper/semantic-lore-repurposer',
  },
  {
    number: '04',
    name: 'Aesthetic Bible Flow',
    type: 'system',
    kind: 'Art direction system',
    status: 'Curated build',
    summary: 'An AI-assisted workspace for aesthetic bibles, mood boards, UI tokens, and cohesion audits.',
    useCase: 'Turns a vague visual instinct into a shared language a team can actually reuse.',
    tags: ['Gemini', 'Vite', 'Design ops'],
    accent: 'blue',
    repoUrl: 'https://github.com/irgendjemandkeinkorper/aesthetic-bible-flow-generator',
    demoUrl: 'https://irgendjemandkeinkorper.github.io/aesthetic-bible-flow-generator/',
  },
  {
    number: '05',
    name: 'Photo Poetry',
    type: 'tool',
    kind: 'Creative tool',
    status: 'Client-side app',
    summary: 'A quiet composition tool for pairing photography with poetry, type, and a little atmosphere.',
    useCase: 'Lets a feeling become a shareable artifact without a backend, account, or workflow tax.',
    tags: ['Angular', 'Canvas 2D', 'Export'],
    accent: 'pink',
    repoUrl: 'https://github.com/irgendjemandkeinkorper/angular-aphotorisms',
  },
  {
    number: '06',
    name: 'AI Subscription Tracker',
    type: 'system',
    kind: 'Personal utility',
    status: 'Local-first dashboard',
    summary: 'A small dashboard for tracking AI quotas, usage, analytics, and portable backups.',
    useCase: 'Makes recurring tool costs visible before they turn into surprise costs.',
    tags: ['Local storage', 'Analytics', 'Privacy'],
    accent: 'yellow',
    repoUrl: 'https://github.com/irgendjemandkeinkorper/ai-subscription-usage-tracker',
  },
  {
    number: '07',
    name: 'Supe Pines',
    type: 'game',
    kind: 'Tabletop story game',
    status: 'Playable online',
    summary: 'A one-session, card-driven story game about street-level heroes and the flaws their cases exploit.',
    useCase: 'Uses a browser as a shared table: enough structure to start, enough room to invent.',
    tags: ['Vanilla JS', 'Firebase', 'Game design'],
    accent: 'red',
    repoUrl: 'https://github.com/irgendjemandkeinkorper/supe-pines',
    demoUrl: 'https://irgendjemandkeinkorper.github.io/supe-pines/',
  },
  {
    number: '08',
    name: 'Chordbound',
    type: 'game',
    kind: 'Card game prototype',
    status: 'Engine experiment',
    summary: 'A musical, ten-element digital card game where every spell changes the agreement between players.',
    useCase: 'Tests whether a rules engine can make an abstract relationship feel playable.',
    tags: ['Node test', 'Game engine', 'Prototyping'],
    accent: 'teal',
    repoUrl: 'https://github.com/irgendjemandkeinkorper/chordbound',
  },
  {
    number: '09',
    name: 'Dramgid Lore Gallery',
    type: 'system',
    kind: 'World-building system',
    status: 'Public gallery',
    summary: 'Generated lore art with stable metadata, image URLs, and cross-links back to the source vault.',
    useCase: 'Gives a living knowledge base a visual index without losing its provenance.',
    tags: ['Python', 'GitHub Pages', 'Gemini'],
    accent: 'gold',
    repoUrl: 'https://github.com/irgendjemandkeinkorper/dramgid-lore-gallery',
    demoUrl: 'https://irgendjemandkeinkorper.github.io/dramgid-lore-gallery/',
  },
  {
    number: '10',
    name: 'Bleakwood Vale',
    type: 'game',
    kind: 'Story game',
    status: 'Playable experiment',
    summary: 'A gothic murder-mystery re-skin of a one-session story engine, built for a table that likes secrets.',
    useCase: 'Explores how a strong content frame can make a familiar mechanic feel like a different game.',
    tags: ['Game design', 'Narrative', 'Browser'],
    accent: 'indigo',
    repoUrl: 'https://github.com/irgendjemandkeinkorper/bleakwood-vale',
  },
];
